[package]
name = "magelang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magelang_common = { path = "../magelang_common" }
magelang_syntax = { path = "../magelang_syntax" }
magelang_package = { path = "../magelang_package" }
magelang_semantic = { path = "../magelang_semantic" }
magelang_typecheck = { path = "../magelang_typecheck"}
magelang_compiler = { path = "../magelang_compiler"}
magelang_cranelift = { path = "../magelang_cranelift"}
magelang_wasm = { path = "../magelang_wasm"}
magelang_runner = { path = "../magelang_runner"}
clap = { version = "4.2.1", features = ["derive"] }

