[package]
name = "magelang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magelang_syntax = { path = "../magelang_syntax" }
clap = { version = "4.0", features = ["derive"] }

